Expose config file locations as env vars
factoriotools/factorio-docker pull request #367
Opened 2021-02-01 05:35 UTC by SQLJames

In the [factorio-server-charts](https://github.com/SQLJames/factorio-server-charts), to allow us to specify the config values we are using configmaps, which creates the json file and mounts it to the proper location, however they are Read only files. This poses an issue when the server-id.json is needed to create a public server because it needs rw operations.  I am currently looking into creating a sidecar to copy the files into the proper directory so we can properly rw to the directory. 

But in my digging to resolve this issue, this solution did come up as a potential fix, so I had to ask if your project would be open to accepting a pull request that allows users to specify the location of config files as an ENV variable.

2021-02-01 05:38 UTC, SQLJames commented
Fixes #356

2021-02-01 05:40 UTC, SQLJames commented
I am actually not sure why the automated tests are failing, can someone tell me what is wrong? I was able to build these locally without issue.

2021-02-01 12:13 UTC, SuperSandro2000 commented
Because the script is broken and missing a -t.

2021-02-05 21:53 UTC, SuperSandro2000 requested changes

2021-02-05 21:53 UTC, SuperSandro2000 commented on 0.16/files/docker-entrypoint.sh
> +#-z string True if the string is null
I would prefer if you did not update 0.16 or 0.17. I didn't touch the code in a longer while and don't want to break it. Also the comments are not required and this script is still sh not bash.

2021-02-05 21:53 UTC, SuperSandro2000 commented on 0.18/files/docker-entrypoint.sh
> +#-z string True if the string is null
```suggestion
```

Not required. Please remove them.

2021-02-05 21:53 UTC, SuperSandro2000 commented on 0.18/files/docker-entrypoint.sh
> +mkdir -p $(dirname "$FACTORIO_SERVER_ID_LOCATION")
```suggestion
mkdir -p "$(dirname "$FACTORIO_SERVER_ID_LOCATION")"
```

2021-02-05 21:53 UTC, SuperSandro2000 commented on 0.18/files/docker-entrypoint.sh
> +mkdir -p $(dirname "$FACTORIO_SERVER_ADMIN_LIST")
```suggestion
mkdir -p "$(dirname "$FACTORIO_SERVER_ADMIN_LIST")"
```

2021-02-05 21:53 UTC, SuperSandro2000 commented on 0.18/files/docker-entrypoint.sh
> +mkdir -p $(dirname "$FACTORIO_SERVER_WHITELIST")
```suggestion
mkdir -p "$(dirname "$FACTORIO_SERVER_WHITELIST")"
```

2021-02-05 21:53 UTC, SuperSandro2000 commented on 0.18/files/docker-entrypoint.sh
> +mkdir -p $(dirname "$FACTORIO_SERVER_BANLIST")
```suggestion
mkdir -p "$(dirname "$FACTORIO_SERVER_BANLIST")"
```

2021-02-05 21:55 UTC, SuperSandro2000 commented
CI should be fixed on master and because I cannot push to your branch you need to rebase on master.

2021-02-08 16:58 UTC, SuperSandro2000 commented on 0.16/files/docker-entrypoint.sh
> +  "$@"
Missing final new line.

2021-02-08 16:58 UTC, SuperSandro2000 commented on 0.17/files/docker-entrypoint.sh
> +exec $SU_EXEC /opt/factorio/bin/x64/factorio "${FLAGS[@]}" "$@"
Missing final new line.

2021-02-08 16:59 UTC, SuperSandro2000 commented
Also please never merge master in a PR and squash the commits together.

2021-02-10 02:34 UTC, SQLJames commented
> Also please never merge master in a PR and squash the commits together.

Sorry this was the problem with rebasing off master, I ran into this issue then my existing pull request was already pointing to master. But yes, I will note that for the future.

2021-02-10 22:42 UTC, SuperSandro2000 commented on 0.16/files/docker-entrypoint.sh
> +
```suggestion
```

2021-05-29 14:44 UTC, proegssilb commented
What's the status of this? It looks like there's a failing check for current, but I can't see any logs, and I'm not sure why these changes would fail for one version but not another?

2021-09-02 03:21 UTC, perobertson commented on 1.1/files/docker-entrypoint.sh
> +if [[ -z "${FACTORIO_SERVER_ID_LOCATION:-}" ]]; then
To set default values you could change this if block to

```bash
: ${FACTORIO_SERVER_ID_LOCATION:=/factorio/config/server-id.json}
```

Example:
```
: ${test:=1 2} && echo $test
1 2

: ${test:=3 4} && echo $test
1 2
```
The `:` is to make the command a nop, but the default value still gets set

2021-09-02 14:17 UTC, Fank commented
@SQLJames we did a lot of changes and got rid of the version numbers in the folder structure.
Could you try to do you changes based on the current master?

2022-01-13 08:45 UTC, SQLJames commented
solved on the helm chart. https://github.com/SQLJames/factorio-server-charts/pull/13

2022-01-13 08:45 UTC, closed without merging